### PR TITLE
Fix parameter not visible in Bitwig

### PR DESCRIPTION
**Pull request by ryrun**
Demo plugin for issue #45 in Bitwig don't show any parameters. Parameters needs to be automatable. Currently return always true.

### CODE REVIEW

**Comment by dudk** [comment]
Thanks for checking it in bitwig! Does automation work with this? I assume that host calls dispatch with `HostAutomate` opcode, which isn't handled now.

**Comment by ryrun** [comment]
Yep is working fine, tested in Renoise also:

I think modern DAWs are not so strict when a plugin does not follow the specification.

**Comment by dudk** [comment]
It's good it works! I have a proposal here. Why don't we add a Boolean field in the Parameter structure that we can return here? 

We can make it opt-out, so by default all parameters are automated. Then it should be named something like NotAutomated 🤔

How does it sound to you @ryrun ?

**Comment by ryrun** [comment]
@dudk Yeah, i thought about that, too. I've added this manually to the branch. Currently working on #54

**Comment by dudk** [comment]
Thank you for your contributions, @ryrun! I don't write much code here right now - want to finish refactoring in pipelined.dev/pipe first. After that I plan to switch back here and either build demo delay plug-in or work on instruments - midi processing API.

**Pull request merged**
